### ISSUE TITLE
Consider modifying doto git repo syncing commands to be more git-like

### ISSUE THREAD

**Issue by Dbz** [tksfz/doto2#8]
add a doto remote repo: `doto remote add <remote name> <git url in ssh form or http form>`
remove a doto remote repo: `doto remote remove <remote name>`
list doto remote repos: `doto remotes -v`
pull latest changes: `doto pull <optional remote>`
push latest changes: `doto push <optional remote> <optional force flag>`

**Comment by Dbz** [comment]
If they are mote git like, then people will know how to use it automatically

**Comment by tksfz** [comment]
I think all these exist equivalently via `doto sync`. Is that accurate in your view?

**Comment by Dbz** [comment]
I haven't had the chance to use `doto sync` yet. I do think it's best to stick with the tools that people know if it isn't too much work. I feel like anyone using this is going to be familiar with git. We can keep this open and then explore it later when I start syncing my todo list.

**Comment by tksfz** [comment]
- Git is an inspiration for doto, but it's not the exclusive or even primary inspiration. Doto doesn't need to be implemented using git. Git is just very convenient because it's ubiquitous.
- I like the spirit of pragmatism but I don't think they're well-realized with this request: doto isn't just git so blindly copying git command names is senseless and could actually increase confusion.
- Moreover, there are actually many precedents for git-based tools that don't re-use git's command names: brew and go, among others. In fact, `doto get` is half-inspired by `go get`.
